collections:
  - name: community.general
    source: ./vendor/community-general-11.4.0.tar.gz
    type: file
  - name: ansible.windows
    source: ./vendor/ansible-windows-3.2.0.tar.gz
    type: file
