all:
  children:
    controllers:
      hosts:
        ctrl-linux-01:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    windows:
      hosts:
        ws-01-win:
          ansible_host: 100.81.77.26
          ansible_user: Administrator
          ansible_connection: ssh
          ansible_port: 22
          ansible_shell_type: powershell
          ansible_shell_executable: None
        ws-02-win:
          ansible_host: 100.121.147.30
          ansible_user: garro
          ansible_connection: ssh
          ansible_port: 22
          ansible_shell_type: powershell
          ansible_shell_executable: None

    linux:
      hosts:
        ws-01-linux:
          ansible_host: 100.67.3.75
          ansible_user: whipz
          ansible_connection: ssh
          ansible_port: 22
          ansible_become: true
          ansible_become_method: sudo
          
    macos:
      hosts:
        ws-03-macos:
          ansible_host: 100.110.14.46
          ansible_user: whip_a
          ansible_connection: ssh
          ansible_port: 22
