- name: Clean up UEFI boot entries on ws-01-linux
  hosts: ws-01-linux
  become: true
  tasks:
    - name: Get current boot entries
      ansible.builtin.command:
        cmd: efibootmgr
      register: efiboot_output
      changed_when: false

    - name: Find and Delete 'Intel Volumel' ghost entry
      become: true
      block:
        - name: Find the 'Intel Volumel' ghost entry boot numbers
          ansible.builtin.set_fact:
            ghost_entry_bootnums: "{{ efiboot_output.stdout_lines | map('regex_search', '^Boot(\\d{4})\\*.*?Intel Volumel', '\\1') | select('string') | list }}"

        - name: Delete the ghost boot entries
          ansible.builtin.command:
            cmd: "efibootmgr -b {{ item }} -B"
          loop: "{{ ghost_entry_bootnums }}"
      when: "'Intel Volumel' in efiboot_output.stdout"

    - name: Set a clean and correct boot order
      ansible.builtin.command:
        cmd: "efibootmgr -o 0001,0007" # Assuming 0001 is Windows and 0007 is Ubuntu
