---
- name: Gather facts from Linux
  hosts: linux
  gather_facts: true
  tasks:
    - name: Show kernel and hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} -> {{ ansible_kernel }}, {{ ansible_nodename }}"

- name: Quick info on Windows (via SSH)
  hosts: windows
  gather_facts: false
  tasks:
    - name: Hostname
      ansible.windows.win_command: hostname
      register: h
    - name: Show
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} -> hostname={{ h.stdout }}"
