- name: Linux ping
  hosts: linux
  gather_facts: false
  tasks:
    - name: Ping
      ansible.builtin.ping:

- name: Windows ping (via SSH)
  hosts: windows
  gather_facts: false
  tasks:
 codex/review-ansible-playbooks-for-compatibility-issues-ggqmkz
    - name: Whoami

      ansible.windows.win_command: whoami
