---
- import_playbook: k8s/provision-sealos.yml
- import_playbook: k8s/deploy-langgraph.yml

- name: Verify LangGraph health endpoint
  hosts: controllers
  gather_facts: false
  tasks:
    - name: Wait for LangGraph service to respond
      ansible.builtin.uri:
        url: http://127.0.0.1:30080/health
        method: GET
        status_code: 200
        return_content: true
      register: langgraph_health
      retries: 10
      delay: 12
      until: langgraph_health.status == 200
