---
# Windows → Linux (one-time boot), orchestrated from controller

- name: Windows -> Linux (one-time boot)
  hosts: controllers
  gather_facts: false

  vars:
    win_host: ws-01-win
    linux_host: ws-01-linux

  tasks:
    - name: Trigger to-linux.ps1 on Windows (async; PowerShell-safe)
      ansible.windows.win_shell: |
        powershell -NoProfile -ExecutionPolicy Bypass -File C:\ops\to-linux.ps1
      delegate_to: "{{ win_host }}"
      async: 30
      poll: 0

    - name: Wait for Windows SSH(22) to drop
      ansible.builtin.wait_for:
        host: "{{ hostvars[win_host].ansible_host }}"
        port: 22
        state: drained
        timeout: 240
      delegate_to: localhost

    - name: Wait for Linux SSH(22) to appear
      ansible.builtin.wait_for:
        host: "{{ hostvars[linux_host].ansible_host }}"
        port: 22
        delay: 10
        timeout: 720
      delegate_to: localhost

    - name: Confirm Linux reachable (ping -> pong)
      ansible.builtin.ping:
      delegate_to: "{{ linux_host }}"
