- name: Windows → Linux (one-time boot to Ubuntu via bcdedit), orchestrated from controllers
  hosts: controllers
  gather_facts: false
  vars:
    win_host: ws-01-win
    linux_host: ws-01-linux
    ps_file: 'C:\\ops\\to-linux.ps1'

  tasks:
    - name: Trigger to-linux.ps1 on Windows
      ansible.windows.win_shell: |
        Start-Process -FilePath powershell.exe -ArgumentList '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{{ ps_file }}"' -WindowStyle Hidden
      delegate_to: "{{ win_host }}"
      async: 30
      poll: 0

    - name: Wait for Windows SSH to drop
      ansible.builtin.wait_for:
        host: "{{ hostvars[win_host].ansible_host }}"
        port: 22
        state: drained
        timeout: 240
      delegate_to: localhost

    - name: Wait for Linux SSH to appear
      ansible.builtin.wait_for:
        host: "{{ hostvars[linux_host].ansible_host }}"
        port: 22
        delay: 10
        timeout: 600
      delegate_to: localhost

    - name: Confirm Linux reachable
      ansible.builtin.ping:
      delegate_to: "{{ linux_host }}"
