- name: Windows → Linux (one-time boot to Ubuntu via bcdedit), orchestrated from control
  hosts: control
  gather_facts: false
  vars:
    win_host: whipx
    linux_host: whipz
    ps_file: 'C:\ops\to-linux.ps1'

  tasks:
    - name: Trigger to-linux.ps1 on Windows
      ansible.windows.win_shell: |
 codex/review-ansible-playbooks-for-compatibility-issues-cb34f1
        Start-Process -FilePath powershell.exe -ArgumentList '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{{ ps_file }}"' -WindowStyle Hidden
        
 main
      delegate_to: "{{ win_host }}"

    - name: Wait for Windows SSH to drop
      ansible.builtin.wait_for:
        host: "{{ hostvars[win_host].ansible_host }}"
        port: 22
        state: drained
        timeout: 240
      delegate_to: localhost

    - name: Wait for Linux SSH to appear
      ansible.builtin.wait_for:
        host: "{{ hostvars[linux_host].ansible_host }}"
        port: 22
        delay: 10
        timeout: 600
      delegate_to: localhost

    - name: Confirm Linux reachable
      ansible.builtin.ping:
      delegate_to: "{{ linux_host }}"
