---
# Decide current OS and trigger the opposite switch.
# Inventory groups: controllers / windows(ws-01-win) / linux(ws-01-linux)

- name: Smartly Toggle OS on ws-01 (decide & switch)
  hosts: controllers
  gather_facts: false

  vars:
    repo_root: "{{ playbook_dir }}/.."   # repo root for nested calls

  tasks:
    # ------ Probe Linux ------
    - name: Probe ws-01-linux via ping (expect 'pong')
      ansible.builtin.ping:
      delegate_to: ws-01-linux
      register: linux_probe
      ignore_unreachable: true

    - name: Set linux_is_online fact
      ansible.builtin.set_fact:
        linux_is_online: "{{ (linux_probe is defined) and (linux_probe.ping | default('') == 'pong') }}"

    # ------ Probe Windows ------
    - name: Probe ws-01-win via 'hostname' (SSH-friendly)
      ansible.builtin.command:
        cmd: hostname
      delegate_to: ws-01-win
      register: win_probe
      ignore_unreachable: true

    - name: Set windows_is_online fact
      ansible.builtin.set_fact:
        windows_is_online: "{{ (win_probe is defined) and (win_probe.rc | default(1) == 0) }}"

    - name: Show probe summary
      ansible.builtin.debug:
        msg:
          linux_is_online: "{{ linux_is_online | default(false) }}"
          windows_is_online: "{{ windows_is_online | default(false) }}"

    # ------ Decide & Switch ------
    - name: Switch to Linux (Windows online & Linux offline)
      ansible.builtin.command:
        cmd: ansible-playbook -i inventory/hosts.yaml playbooks/switch-to-linux.yml
        chdir: "{{ repo_root }}"
      when: (windows_is_online | default(false)) and not (linux_is_online | default(false))
      changed_when: true

    - name: Switch to Windows (Linux online & Windows offline)
      ansible.builtin.command:
        cmd: ansible-playbook -i inventory/hosts.yaml playbooks/switch-to-windows.yml
        chdir: "{{ repo_root }}"
      when: (linux_is_online | default(false)) and not (windows_is_online | default(false))
      changed_when: true

    # ------ Edge cases ------
    - name: Both offline → fail
      ansible.builtin.fail:
        msg: "Both ws-01-linux and ws-01-win are unreachable. Please check machine power / network."
      when: not (linux_is_online | default(false)) and not (windows_is_online | default(false))

    - name: Both online → no-op
      ansible.builtin.debug:
        msg: "Both ws-01-linux and ws-01-win appear online. Not toggling (no-op)."
      when: (linux_is_online | default(false)) and (windows_is_online | default(false))
