---
- name: Smartly Toggle OS on ws-01 (decide & switch)
  hosts: controllers
  gather_facts: false

  vars:
    repo_root: "{{ playbook_dir }}/.."   # 仓库根，便于子 playbook chdir

  tasks:
    # ------ Probe Linux ------
    - name: Probe ws-01-linux via ping (expect 'pong')
      ansible.builtin.ping:
      delegate_to: ws-01-linux
      register: linux_probe
      ignore_unreachable: true

    - name: Set linux_is_online fact
      ansible.builtin.set_fact:
        linux_is_online: "{{ (linux_probe is defined) and (linux_probe.ping | default('') == 'pong') }}"

    # ------ Probe Windows ------
    - name: Probe ws-01-win via win_ping (most reliable for SSH)
      ansible.windows.win_ping:
      delegate_to: ws-01-win
      register: win_probe
      ignore_unreachable: true

    - name: Set windows_is_online fact
      ansible.builtin.set_fact:
        windows_is_online: "{{ (win_probe is defined) and (win_probe.ping | default('') == 'pong') }}"

    - name: Show probe summary
      ansible.builtin.debug:
        msg:
          linux_is_online: "{{ linux_is_online | default(false) }}"
          windows_is_online: "{{ windows_is_online | default(false) }}"

    # ------ Decide & Switch ------
    - name: Decide and Switch to Linux (if Windows online, Linux offline)
      ansible.builtin.command:
        cmd: "ansible-playbook -i inventory/hosts.yaml playbooks/switch-to-linux.yml"
        chdir: "{{ repo_root }}"
      when: (windows_is_online | default(false)) and not (linux_is_online | default(false))
      changed_when: true

    - name: Decide and Switch to Windows (if Linux online, Windows offline)
      ansible.builtin.command:
        cmd: "ansible-playbook -i inventory/hosts.yaml playbooks/switch-to-windows.yml"
        chdir: "{{ repo_root }}"
      when: (linux_is_online | default(false)) and not (windows_is_online | default(false))
      changed_when: true

    # ------ Report edge cases ------
    - name: Report if both systems are offline
      ansible.builtin.fail:
        msg: "Both ws-01-linux and ws-01-win are unreachable. Please check the machine's power state."
      when: not (linux_is_online | default(false)) and not (windows_is_online | default(false))

    - name: Report if both systems appear online
      ansible.builtin.debug:
        msg: "Both ws-01-linux and ws-01-win appear online. Not toggling (no-op)."
      when: (linux_is_online | default(false)) and (windows_is_online | default(false))
