---
# 目的：智能判断 ws-01 当前运行在哪个 OS，并触发相反方向的切换
# 约定：
#   - Linux 主机：ws-01-linux
#   - Windows 主机：ws-01-win
#   - 切换剧本已存在：playbooks/switch-to-linux.yml / playbooks/switch-to-windows.yml

- name: Smartly Toggle OS on ws-01 (decide & switch)
  hosts: controllers
  gather_facts: false

  vars:
    repo_root: "{{ playbook_dir }}/.."

  tasks:
    # ------ Probe Linux ------
    - name: Probe ws-01-linux via ping
      ansible.builtin.ping:
      delegate_to: ws-01-linux
      register: linux_probe
      ignore_unreachable: true

    - name: Set linux_is_online fact
      ansible.builtin.set_fact:
        linux_is_online: "{{ not linux_probe.unreachable | default(true) }}"

    # ------ Probe Windows ------
    - name: Probe ws-01-win via hostname (using win_shell)
      ansible.windows.win_shell: hostname
      delegate_to: ws-01-win
      register: win_probe
      ignore_unreachable: true

    - name: Set windows_is_online fact
      ansible.builtin.set_fact:
        # 修正点：使用更可靠的方式来判断 Windows 是否在线
        windows_is_online: "{{ win_probe is not unreachable and win_probe is not failed }}"

    - name: Show probe summary
      ansible.builtin.debug:
        msg:
          linux_is_online: "{{ linux_is_online | default(false) }}"
          windows_is_online: "{{ windows_is_online | default(false) }}"

    # ------ Decide & Switch ------
    - name: Decide and Switch to Linux (if Windows online, Linux offline)
      ansible.builtin.command:
        cmd: "ansible-playbook -i ../inventory/hosts.yaml switch-to-linux.yml"
        chdir: "{{ playbook_dir }}"
      when: (windows_is_online | default(false)) and not (linux_is_online | default(false))
      changed_when: true

    - name: Decide and Switch to Windows (if Linux online, Windows offline)
      ansible.builtin.command:
        cmd: "ansible-playbook -i ../inventory/hosts.yaml switch-to-windows.yml"
        chdir: "{{ playbook_dir }}"
      when: (linux_is_online | default(false)) and not (windows_is_online | default(false))
      changed_when: true

    # ------ Report edge cases ------
    - name: Report if both systems are offline
      ansible.builtin.fail:
        msg: "Both ws-01-linux and ws-01-win are unreachable. Please check the machine's power state."
      when: not (linux_is_online | default(false)) and not (windows_is_online | default(false))

    - name: Report if both systems appear online
      ansible.builtin.debug:
        msg: "Both ws-01-linux and ws-01-win appear online. Not toggling (no-op)."
      when: (linux_is_online | default(false)) and (windows_is_online | default(false))
