---
name: Auto-Deploy Observability Stack

on:
  push:
    branches:
      - main
    paths:  # 只有当日志相关的剧本或模板文件发生变化时，才触发
      - 'playbooks/deploy-observability-stack.yml'
      - 'templates/config.alloy.j2'
      - 'templates/grafana-datasource-loki.yml.j2'

jobs:
  auto-deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 3. Run the observability stack deployment
        run: ansible-playbook -i inventory/hosts.yaml playbooks/deploy-observability-stack.yml
