name: Everyone Is Here (System-Wide Health Check)

on:
  workflow_dispatch:

jobs:
  health-check:
    runs-on: self-hosted
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup SSH Key for Ansible
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: 3. Install Ansible dependencies
        run: ansible-galaxy collection install -r requirements.yml

      - name: 4. Lock Kernel on Linux Controller
        run: ansible-playbook -i inventory/hosts.yaml playbooks/lock-controller-kernel.yml

      - name: 5. Lock Kernel on Linux Workstation
        run: ansible-playbook -i inventory/hosts.yaml playbooks/lock-kernel.yml -l ws-01-linux
      
      - name: 6. Ping macOS Host
        run: ansible -i inventory/hosts.yaml macos -m ansible.builtin.ping
        
      - name: 7. Ping Windows Hosts
        run: ansible -i inventory/hosts.yaml windows -m ansible.windows.win_ping
