name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup SSH Key for Ansible
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: 3. Install Ansible dependencies
        run: ansible-galaxy collection install -r requirements.yml

      - name: 4. Lock Kernel Version on ws-01-linux
        run: ansible-playbook -i inventory/hosts.yaml playbooks/lock-kernel.yml -l ws-01-linux
