name: Ansible PR Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  gate1-static:
    name: Gate 1 - lint & local tests
    runs-on: [self-hosted, ansible, hardware]
    steps:
      - uses: actions/checkout@v4
      - name: Setup runner tools
        run: make setup
      - name: Run make lint
        run: make lint
      - name: Run make test
        run: make test

  gate2-integration:
    name: Gate 2 - integration (machine-verifiable)
    needs: gate1-static
    runs-on: [self-hosted, ansible, hardware]
    steps:
      - uses: actions/checkout@v4
      - name: Run make itest
        run: make itest
      - name: Upload itest artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: itest-artifacts
          path: artifacts/itest

  deploy:
    name: Deploy on success
    needs: gate2-integration
    if: needs.gate2-integration.result == 'success'
    runs-on: [self-hosted, ansible, hardware]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: make deploy
