---
name: "HomeOps PR Quality Gates"

'on':
  pull_request:
    branches: ["main"]

jobs:
  gate1-cloud:
    name: Gate1 (cloud) — lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Gate0 — make setup
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
        run: make setup

      - name: Show tool versions
        shell: bash
        run: |
          cat artifacts/test/tools_versions.txt

      - name: Gate1.1 — make lint
        env:
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make lint

      - name: Gate1.2 — make test
        env:
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make test

      - name: Upload Gate1 artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gate1-artifacts
          path: artifacts/test
          if-no-files-found: warn

  gate2-selfhosted:
    name: Gate2 (self-hosted) — deploy & verify
    needs: gate1-cloud
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH credentials
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Gate2 — make itest
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make itest

      - name: Upload Gate2 artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gate2-artifacts
          path: |
            artifacts/test
            artifacts/itest
          if-no-files-found: warn
