name: HomeOps Quality Gates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  quality:
    name: Quality Gates (Gate0→Gate2 + Conditional Deploy)
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap ansible toolchain (missing-safe)
        shell: bash
        run: |
          set -euo pipefail
          # Ensure Python + venv
          if ! command -v python3 >/dev/null 2>&1; then
            if command -v apt-get >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y python3 python3-venv python3-pip
            elif command -v dnf >/dev/null 2>&1; then
              sudo dnf install -y python3 python3-virtualenv python3-pip || true
            elif command -v yum >/dev/null 2>&1; then
              sudo yum install -y python3 python3-virtualenv python3-pip || true
            fi
          fi

          # Create venv and install toolchain (idempotent)
          if [ ! -d ".venv" ]; then
            python3 -m venv .venv
          fi
          source .venv/bin/activate
          python -m pip install -U pip wheel
          python -m pip install "ansible-core>=2.16" "ansible-lint>=24.0" "yamllint>=1.32"
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Show tool versions
        shell: bash
        run: |
          source .venv/bin/activate
          echo "ansible      : $(ansible --version | head -n1)"
          echo "ansible-lint : $(ansible-lint --version | head -n1)"
          echo "yamllint     : $(yamllint --version)"

      - name: Gate 0 - make setup
        shell: bash
        run: make setup

      - name: Gate 1.1 - make lint
        shell: bash
        run: make lint

      - name: Gate 1.2 - make test
        shell: bash
        run: make test

      - id: itest
        name: Gate 2 - make itest (runs only if verify playbook exists)
        if: ${{ success() && hashFiles('playbooks/tests/verify_observability.yml') != '' }}
        shell: bash
        run: make itest

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: homeops-artifacts
          path: |
            artifacts/test
            artifacts/itest
          if-no-files-found: ignore

      - name: Deploy (conditional after successful Gate 2; push to main only)
        if: ${{ steps.itest.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' && hashFiles('playbooks/deploy-observability-stack.yml') != '' }}
        shell: bash
        run: make deploy
