name: HomeOps Quality Gates (Option A: venv outside repo)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gate1-cloud:
    name: Gate1 (cloud) — lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap venv in runner temp (PEP668-safe)
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y python3 python3-venv python3-pip
          VENV="${{ runner.temp }}/venv_homeops"
          python3 -m venv "$VENV"
          . "$VENV/bin/activate"
          python -m pip install -U pip wheel
          python -m pip install "ansible-core>=2.16" "ansible-lint>=24.0" "yamllint>=1.32"
          echo "$VENV/bin" >> "$GITHUB_PATH"

      - name: Show tool versions
        shell: bash
        run: |
          ansible --version | head -n1 || true
          ansible-lint --version || true
          yamllint --version || true

      - name: Gate1.1 — make lint
        env:
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make lint

      - name: Gate1.2 — make test
        env:
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make test

  gate2-selfhosted:
    name: Gate2 (self-hosted) — itest + conditional deploy
    needs: gate1-cloud
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Ensure venv in runner temp
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v python3 >/dev/null 2>&1; then
            echo "python3 missing on runner" >&2
            exit 2
          fi
          VENV="${{ runner.temp }}/venv_homeops"
          python3 -m venv "$VENV" || true
          . "$VENV/bin/activate" || true
          python -m pip install -U pip wheel || true
          python -m pip install "ansible-core>=2.16" "ansible-lint>=24.0" "yamllint>=1.32" || true
          echo "$VENV/bin" >> "$GITHUB_PATH"

      - name: Gate2 — make itest
        env:
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make itest

      - name: Upload itest artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: itest-artifacts
          path: artifacts/itest
          if-no-files-found: ignore

      - name: Deploy (only when explicitly enabled)
        if: ${{ success() && vars.AUTO_DEPLOY == 'true' }}
        env:
          ANSIBLE_STDOUT_CALLBACK: ansible.builtin.yaml
        run: make deploy
