name: Smart Toggle OS

on:
  workflow_dispatch:

concurrency:
  group: toggle-os
  cancel-in-progress: false

jobs:
  toggle-os:
    runs-on: self-hosted
    timeout-minutes: 45

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 3. Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: 4. Run the smart toggle playbook
        run: ansible-playbook -i inventory/hosts.yaml playbooks/toggle-os.yml -vv
